version: "3.3"
services:
  shortener-discord-bot:
    image: "xtiltedboy/shortener-discord-bot"
    container_name: shortener-discord-bot
    pull_policy: build
    build: 
      context: .
    restart: always 
    volumes:
      - /mnt/datos/shortener-discord-bot/:/shortener-discord-bot
    network_mode: "host"
    environment:
      - token
