version: "3.3"
services:
  greybot:
    container_name: shortener-discord-bot
    pull_policy: build
    build: 
      context: .
    restart: always 
    volumes:
      - .:/shortener-discord-bot
    network_mode: "host"
